# Generated by Django 5.2.7 on 2025-11-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
